apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.vaultUrl | quote }}
      tenantId: {{ .Values.tenantId | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: torqvoice
  labels:
    app: torqvoice
    part-of: torqvoice
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: torqvoice
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .Values.dbUser }}:{{ `{{ .password | urlquery }}` }}@{{ .Values.dbHost }}:5432/{{ .Values.dbName }}?sslmode=require"
        BETTER_AUTH_SECRET: '{{ `{{ .better_auth }}` }}'
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.kvPassword | quote }}
    - secretKey: better_auth
      remoteRef:
        key: {{ .Values.kvAuth | quote }}
